##For working with variables set in .env.example
version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: conqdb-dev
    ports:
      - '5432:5432'
